---
- name: Configure SNMPv3 users on Cisco MDS switches
  hosts: mds_switches
  gather_facts: no

  tasks:
    - name: Include SNMPv3 variables
      include_vars: snmpv3_vars.yml

    - name: Configure SNMPv3 group
      cisco.nxos.nxos_snmp_group:
        group: "{{ snmpv3_group }}"
        version: v3
        auth: "{{ snmpv3_auth }}"
        priv: "{{ snmpv3_priv }}"
        state: present

    - name: Configure SNMPv3 user
      cisco.nxos.nxos_snmp_user:
        user: "{{ snmpv3_user }}"
        group: "{{ snmpv3_group }}"
        auth_protocol: "{{ snmpv3_auth_protocol }}"
        auth_key: "{{ snmpv3_auth_key }}"
        priv_protocol: "{{ snmpv3_priv_protocol }}"
        priv_key: "{{ snmpv3_priv_key }}"
        state: present

    - name: Save running configuration to startup configuration
      cisco.nxos.nxos_config_save:
        destination: "startup-config"
